In [1]:
from SpaGE.main import SpaGE

In [2]:
import scanpy as sc
data_path = '../dataset/Chromium_FFPE_Human_Breast_Cancer_Chromium_FFPE_Human_Breast_Cancer_count_sample_filtered_feature_bc_matrix.h5'
sc_data = sc.read_10x_h5(data_path)
sc_data.X = sc_data.X.toarray()
sc.pp.normalize_total(sc_data)
sc.pp.log1p(sc_data)

/home/hanchuangyi/miniconda3/envs/tangram/lib/python3.10/site-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")

/home/hanchuangyi/miniconda3/envs/tangram/lib/python3.10/site-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")

In [3]:
st_data_path = '../dataset/Xenium_breast_cancer_sample1_replicate1.h5ad'
st_data = sc.read_h5ad(st_data_path)
sc.pp.normalize_total(st_data)
sc.pp.log1p(st_data)
st_data

/home/hanchuangyi/miniconda3/envs/tangram/lib/python3.10/site-packages/scanpy/preprocessing/_normalization.py:235: UserWarning: Some cells have zero counts
  warn(UserWarning("Some cells have zero counts"))

AnnData object with n_obs × n_vars = 167780 × 313
    obs: 'cell_type', 'cell_id', 'x_centroid', 'y_centroid', 'transcript_counts', 'control_probe_counts', 'control_codeword_counts', 'total_counts', 'cell_area', 'nucleus_area'
    var: 'gene_ids', 'feature_types', 'genome'
    uns: 'BT_FT_predictions_3407', 'BT_FT_predictions_42', 'BT_FT_predictions_476', 'BT_FT_predictions_761', 'BT_FT_predictions_9824', 'BT_FT_target_names_3407', 'BT_FT_target_names_42', 'BT_FT_target_names_476', 'BT_FT_target_names_761', 'BT_FT_target_names_9824', 'BT_FT_train_loss_3407', 'BT_FT_train_loss_42', 'BT_FT_train_loss_476', 'BT_FT_train_loss_761', 'BT_FT_train_loss_9824', 'BT_FT_val_loss_3407', 'BT_FT_val_loss_42', 'BT_FT_val_loss_476', 'BT_FT_val_loss_761', 'BT_FT_val_loss_9824', 'BT_FT_y_test_3407', 'BT_FT_y_test_42', 'BT_FT_y_test_476', 'BT_FT_y_test_761', 'BT_FT_y_test_9824', 'BT_ZS_predictions_3407', 'BT_ZS_predictions_42', 'BT_ZS_predictions_476', 'BT_ZS_predictions_761', 'BT_ZS_predictions_9824', 'BT_ZS_target_names_3407', 'BT_ZS_target_names_42', 'BT_ZS_target_names_476', 'BT_ZS_target_names_761', 'BT_ZS_target_names_9824', 'BT_ZS_y_test_3407', 'BT_ZS_y_test_42', 'BT_ZS_y_test_476', 'BT_ZS_y_test_761', 'BT_ZS_y_test_9824', 'GP_FT_predictions_3407', 'GP_FT_predictions_42', 'GP_FT_predictions_476', 'GP_FT_predictions_761', 'GP_FT_predictions_9824', 'GP_FT_target_names_3407', 'GP_FT_target_names_42', 'GP_FT_target_names_476', 'GP_FT_target_names_761', 'GP_FT_target_names_9824', 'GP_FT_train_loss_3407', 'GP_FT_train_loss_42', 'GP_FT_train_loss_476', 'GP_FT_train_loss_761', 'GP_FT_train_loss_9824', 'GP_FT_val_loss_3407', 'GP_FT_val_loss_42', 'GP_FT_val_loss_476', 'GP_FT_val_loss_761', 'GP_FT_val_loss_9824', 'GP_FT_y_test_3407', 'GP_FT_y_test_42', 'GP_FT_y_test_476', 'GP_FT_y_test_761', 'GP_FT_y_test_9824', 'GP_ZS_predictions_3407', 'GP_ZS_predictions_42', 'GP_ZS_predictions_476', 'GP_ZS_predictions_761', 'GP_ZS_predictions_9824', 'GP_ZS_target_names_3407', 'GP_ZS_target_names_42', 'GP_ZS_target_names_476', 'GP_ZS_target_names_761', 'GP_ZS_target_names_9824', 'GP_ZS_y_test_3407', 'GP_ZS_y_test_42', 'GP_ZS_y_test_476', 'GP_ZS_y_test_761', 'GP_ZS_y_test_9824', 'PCA_predictions_3407', 'PCA_predictions_42', 'PCA_predictions_476', 'PCA_predictions_761', 'PCA_predictions_9824', 'PCA_target_names_3407', 'PCA_target_names_42', 'PCA_target_names_476', 'PCA_target_names_761', 'PCA_target_names_9824', 'PCA_y_test_3407', 'PCA_y_test_42', 'PCA_y_test_476', 'PCA_y_test_761', 'PCA_y_test_9824', 'RM_FT_predictions_3407', 'RM_FT_predictions_42', 'RM_FT_predictions_476', 'RM_FT_predictions_761', 'RM_FT_predictions_9824', 'RM_FT_target_names_3407', 'RM_FT_target_names_42', 'RM_FT_target_names_476', 'RM_FT_target_names_761', 'RM_FT_target_names_9824', 'RM_FT_train_loss_3407', 'RM_FT_train_loss_42', 'RM_FT_train_loss_476', 'RM_FT_train_loss_761', 'RM_FT_train_loss_9824', 'RM_FT_val_loss_3407', 'RM_FT_val_loss_42', 'RM_FT_val_loss_476', 'RM_FT_val_loss_761', 'RM_FT_val_loss_9824', 'RM_FT_y_test_3407', 'RM_FT_y_test_42', 'RM_FT_y_test_476', 'RM_FT_y_test_761', 'RM_FT_y_test_9824', 'RM_ZS_predictions_3407', 'RM_ZS_predictions_42', 'RM_ZS_predictions_476', 'RM_ZS_predictions_761', 'RM_ZS_predictions_9824', 'RM_ZS_target_names_3407', 'RM_ZS_target_names_42', 'RM_ZS_target_names_476', 'RM_ZS_target_names_761', 'RM_ZS_target_names_9824', 'RM_ZS_y_test_3407', 'RM_ZS_y_test_42', 'RM_ZS_y_test_476', 'RM_ZS_y_test_761', 'RM_ZS_y_test_9824', 'supervised_predictions_3407', 'supervised_predictions_42', 'supervised_predictions_476', 'supervised_predictions_761', 'supervised_predictions_9824', 'supervised_target_names_3407', 'supervised_target_names_42', 'supervised_target_names_476', 'supervised_target_names_761', 'supervised_target_names_9824', 'supervised_train_loss_3407', 'supervised_train_loss_42', 'supervised_train_loss_476', 'supervised_train_loss_761', 'supervised_train_loss_9824', 'supervised_val_loss_3407', 'supervised_val_loss_42', 'supervised_val_loss_476', 'supervised_val_loss_761', 'supervised_val_loss_9824', 'supervised_y_test_3407', 'supervised_y_test_42', 'supervised_y_test_476', 'supervised_y_test_761', 'supervised_y_test_9824', 'log1p'
    obsm: 'PCA_3407', 'PCA_42', 'PCA_476', 'PCA_761', 'PCA_9824', 'RM_FT', 'SSL_BT_FT', 'SSL_BT_FT_3407', 'SSL_BT_FT_42', 'SSL_BT_FT_476', 'SSL_BT_FT_761', 'SSL_BT_FT_9824', 'SSL_BT_ZS_3407', 'SSL_BT_ZS_42', 'SSL_BT_ZS_476', 'SSL_BT_ZS_761', 'SSL_BT_ZS_9824', 'SSL_GP_FT_3407', 'SSL_GP_FT_42', 'SSL_GP_FT_476', 'SSL_GP_FT_761', 'SSL_GP_FT_9824', 'SSL_GP_ZS_3407', 'SSL_GP_ZS_42', 'SSL_GP_ZS_476', 'SSL_GP_ZS_761', 'SSL_GP_ZS_9824', 'SSL_RM_FT_3407', 'SSL_RM_FT_42', 'SSL_RM_FT_476', 'SSL_RM_FT_761', 'SSL_RM_FT_9824', 'SSL_RM_ZS_3407', 'SSL_RM_ZS_42', 'SSL_RM_ZS_476', 'SSL_RM_ZS_761', 'SSL_RM_ZS_9824', 'spatial', 'supervised_3407', 'supervised_42', 'supervised_476', 'supervised_761', 'supervised_9824'

In [4]:
# 检查 sc_data.var_names 是否有重复项
duplicates = sc_data.var_names[sc_data.var_names.duplicated()]
print(f"重复的基因: {duplicates}")
# 删除 sc_data.var_names 中的重复基因
sc_data = sc_data[:, ~sc_data.var_names.duplicated()]

重复的基因: Index(['TBCE', 'HSPA14', 'TMSB15B'], dtype='object')

In [5]:
st_data.X = st_data.X.toarray()

In [6]:
import pandas as pd
sc_df = pd.DataFrame(sc_data.X, index=sc_data.obs.index,columns=sc_data.var.index)
sc_df

,SAMD11,NOC2L,KLHL17,PLEKHN1,PERM1,HES4,ISG15,AGRN,RNF223,C1orf159,...,MT-ND2,MT-CO2,MT-ATP6,MT-CO3,MT-ND3,MT-ND4L,MT-ND4,MT-ND5,MT-ND6,MT-CYB
AAACAAGCAAACGGGA-1,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.000000,...,1.574241,2.902621,0.000000,2.902621,0.000000,1.908151,1.908151,1.574241,3.002478,1.908151
AAACAAGCAAATAGGA-1,0.431731,0.238986,0.000000,0.000000,0.0,0.000000,0.431731,0.431731,0.0,0.000000,...,1.061161,2.047566,0.593261,2.534356,1.308226,2.421124,1.619271,0.963084,1.813073,2.012106
AAACAAGCAAATGACT-1,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.000000,...,1.319668,3.601367,0.000000,2.859515,1.319668,2.688588,0.000000,0.000000,0.000000,2.482296
AAACAAGCAACAAGTT-1,0.000000,0.000000,0.000000,0.000000,0.0,0.945020,0.945020,1.422079,0.0,0.000000,...,0.945020,1.743723,0.000000,1.743723,0.945020,2.182034,1.422079,0.945020,1.422079,0.000000
AAACAAGCAACCATTC-1,1.002375,0.000000,0.000000,0.454201,0.0,1.193819,0.765388,1.002375,0.0,0.000000,...,1.354436,2.478501,0.765388,2.570565,0.000000,2.136990,1.722645,0.765388,1.722645,1.492789
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
TTTGTGAGTGGTTACT-1,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,1.077854,0.000000,0.0,0.000000,...,1.819533,2.536091,0.000000,3.045940,0.829531,2.585982,1.708895,0.829531,1.077854,2.240666
TTTGTGAGTGTTCCAG-1,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.000000,...,1.195101,1.724155,0.000000,1.724155,0.000000,2.323912,1.195101,1.724155,2.068339,2.323912
TTTGTGAGTTACTTCT-1,0.144048,0.144048,0.144048,0.000000,0.0,0.381731,0.269935,0.381731,0.0,0.144048,...,1.784746,2.830785,0.381731,3.087255,1.050568,3.148938,1.929738,0.935856,2.784028,2.535320
TTTGTGAGTTGTCATA-1,0.000000,0.000000,0.000000,0.567252,0.0,0.000000,0.000000,1.399620,0.0,0.000000,...,0.567252,2.458546,1.190962,2.878924,1.190962,2.155725,1.847494,0.567252,1.719276,0.926965
TTTGTGAGTTTGGCCA-1,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.688389,0.0,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,1.379149,0.000000,0.000000,0.688389,0.000000

In [7]:
st_df = pd.DataFrame(st_data.X, index=st_data.obs.index, columns=st_data.var.index)
st_df

,ABCC11,ACTA2,ACTG2,ADAM9,ADGRE5,ADH1B,ADIPOQ,AGR3,AHSP,AIF1,...,TUBB2B,TYROBP,UCP1,USP53,VOPP1,VWF,WARS,ZEB1,ZEB2,ZNF562
1,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.0,0.000000,...,0.0,0.000000,0.0,0.000000,0.000000,0.0,1.935654,0.0,0.000000,0.000000
2,0.000000,0.000000,1.017387,0.0,0.0,0.000000,0.0,1.511145,0.0,0.000000,...,0.0,0.000000,0.0,1.840212,0.000000,0.0,0.000000,0.0,0.000000,0.000000
3,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.0,0.000000,...,0.0,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000
4,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.0,0.000000,...,0.0,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000
5,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.0,2.068970,...,0.0,1.494775,0.0,2.068970,0.000000,0.0,0.000000,0.0,1.494775,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
167776,0.895999,0.545164,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.0,0.895999,...,0.0,0.000000,0.0,0.000000,0.895999,0.0,0.000000,0.0,0.000000,0.545164
167777,0.000000,1.131810,1.131810,0.0,0.0,0.000000,0.0,0.000000,0.0,0.000000,...,0.0,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000
167778,0.983031,0.349343,1.128391,0.0,0.0,0.000000,0.0,0.349343,0.0,0.000000,...,0.0,0.000000,0.0,0.607737,0.607737,0.0,0.000000,0.0,0.000000,0.812887
167779,0.883273,0.000000,0.000000,0.0,0.0,0.883273,0.0,0.000000,0.0,0.000000,...,0.0,0.000000,0.0,0.883273,0.000000,0.0,0.000000,0.0,0.000000,0.000000
167780,1.014003,0.364055,0.840472,0.0,0.0,0.000000,0.0,0.364055,0.0,0.000000,...,0.0,0.000000,0.0,0.000000,0.840472,0.0,0.000000,0.0,0.000000,0.000000

In [8]:
# Check for NaN values in both dataframes
print("NaN values in sc_df:", sc_df.isna().sum().sum())
print("NaN values in st_df:", st_df.isna().sum().sum())

# Fill NaN values with zeros if they exist
if sc_df.isna().sum().sum() > 0:
    print("Filling NaN values in sc_df with zeros")
    sc_df = sc_df.fillna(0)

if st_df.isna().sum().sum() > 0:
    print("Filling NaN values in st_df with zeros")
    st_df = st_df.fillna(0)

# Verify no more NaNs exist
print("After filling, NaN values in sc_df:", sc_df.isna().sum().sum())
print("After filling, NaN values in st_df:", st_df.isna().sum().sum())

NaN values in sc_df: 0
NaN values in st_df: 0

After filling, NaN values in sc_df: 0
After filling, NaN values in st_df: 0

In [9]:
imputed_genes = SpaGE(Spatial_data=st_df, RNA_data=sc_df, n_pv=5)
imputed_genes

Genes to predict:  ['A1CF' 'A2M' 'A2ML1' ... 'ZYG11B' 'ZYX' 'ZZEF1']

Spatial_data_scaled NaN values:  0

RNA_data_scaled NaN values:  11720890

Spatial_data_scaled NaN values after filling:  0

RNA_data_scaled NaN values after filling:  0
Common_data NaN values:  0

/home/hanchuangyi/miniconda3/envs/tangram/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3785: FutureWarning: The behavior of DataFrame.var with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return var(axis=axis, dtype=dtype, out=out, ddof=ddof, **kwargs)
/home/hanchuangyi/miniconda3/envs/tangram/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3785: FutureWarning: The behavior of DataFrame.var with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return var(axis=axis, dtype=dtype, out=out, ddof=ddof, **kwargs)

,A1CF,A2M,A2ML1,A3GALT2,A4GALT,A4GNT,AAAS,AACS,AADAC,AADACL2,...,ZW10,ZWILCH,ZWINT,ZXDA,ZXDB,ZXDC,ZYG11A,ZYG11B,ZYX,ZZEF1
0,0.0,0.059112,0.0,0.0,0.010386,0.0,0.101798,0.107795,0.000000,0.000000,...,0.031978,0.059419,0.182297,0.011120,0.007420,0.098280,0.094049,0.099743,0.288382,0.110509
1,0.0,0.020419,0.0,0.0,0.008400,0.0,0.167451,0.136574,0.000000,0.000000,...,0.028540,0.086311,0.142404,0.000000,0.021977,0.069789,0.087356,0.083815,0.257820,0.129420
2,0.0,0.059581,0.0,0.0,0.000000,0.0,0.169985,0.068567,0.000000,0.000000,...,0.035149,0.099265,0.150944,0.002313,0.002313,0.085448,0.031803,0.054297,0.204100,0.088955
3,0.0,0.048274,0.0,0.0,0.005519,0.0,0.088812,0.095186,0.000000,0.000000,...,0.057827,0.048809,0.108155,0.000000,0.003850,0.057875,0.097586,0.066907,0.184062,0.062585
4,0.0,0.408509,0.0,0.0,0.004877,0.0,0.150045,0.146439,0.010433,0.000000,...,0.051586,0.030310,0.203676,0.000000,0.018167,0.138590,0.048936,0.106965,0.367621,0.082398
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
167775,0.0,0.154774,0.0,0.0,0.001278,0.0,0.109334,0.099681,0.000000,0.000000,...,0.026316,0.062015,0.209323,0.004633,0.044789,0.095314,0.060517,0.067600,0.245934,0.122871
167776,0.0,0.042010,0.0,0.0,0.007343,0.0,0.133561,0.083587,0.000000,0.000000,...,0.063060,0.070104,0.258507,0.011526,0.037051,0.138651,0.098864,0.084773,0.277775,0.086642
167777,0.0,0.020730,0.0,0.0,0.008564,0.0,0.175115,0.099238,0.000000,0.000000,...,0.078448,0.055241,0.278876,0.032243,0.022218,0.121580,0.085519,0.058569,0.276222,0.078463
167778,0.0,0.014055,0.0,0.0,0.000000,0.0,0.150878,0.130387,0.000000,0.011059,...,0.074299,0.053778,0.168359,0.043058,0.024883,0.106284,0.094542,0.065982,0.259573,0.077460
167779,0.0,0.041095,0.0,0.0,0.003728,0.0,0.148428,0.106508,0.000000,0.000000,...,0.066978,0.053370,0.304215,0.012127,0.019711,0.104122,0.115786,0.049744,0.251808,0.074468

In [10]:
# Convert the index to string type and add 1 to each value
imputed_genes.index = imputed_genes.index + 1
imputed_genes.index = imputed_genes.index.astype(str)
imputed_genes

,A1CF,A2M,A2ML1,A3GALT2,A4GALT,A4GNT,AAAS,AACS,AADAC,AADACL2,...,ZW10,ZWILCH,ZWINT,ZXDA,ZXDB,ZXDC,ZYG11A,ZYG11B,ZYX,ZZEF1
1,0.0,0.059112,0.0,0.0,0.010386,0.0,0.101798,0.107795,0.000000,0.000000,...,0.031978,0.059419,0.182297,0.011120,0.007420,0.098280,0.094049,0.099743,0.288382,0.110509
2,0.0,0.020419,0.0,0.0,0.008400,0.0,0.167451,0.136574,0.000000,0.000000,...,0.028540,0.086311,0.142404,0.000000,0.021977,0.069789,0.087356,0.083815,0.257820,0.129420
3,0.0,0.059581,0.0,0.0,0.000000,0.0,0.169985,0.068567,0.000000,0.000000,...,0.035149,0.099265,0.150944,0.002313,0.002313,0.085448,0.031803,0.054297,0.204100,0.088955
4,0.0,0.048274,0.0,0.0,0.005519,0.0,0.088812,0.095186,0.000000,0.000000,...,0.057827,0.048809,0.108155,0.000000,0.003850,0.057875,0.097586,0.066907,0.184062,0.062585
5,0.0,0.408509,0.0,0.0,0.004877,0.0,0.150045,0.146439,0.010433,0.000000,...,0.051586,0.030310,0.203676,0.000000,0.018167,0.138590,0.048936,0.106965,0.367621,0.082398
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
167776,0.0,0.154774,0.0,0.0,0.001278,0.0,0.109334,0.099681,0.000000,0.000000,...,0.026316,0.062015,0.209323,0.004633,0.044789,0.095314,0.060517,0.067600,0.245934,0.122871
167777,0.0,0.042010,0.0,0.0,0.007343,0.0,0.133561,0.083587,0.000000,0.000000,...,0.063060,0.070104,0.258507,0.011526,0.037051,0.138651,0.098864,0.084773,0.277775,0.086642
167778,0.0,0.020730,0.0,0.0,0.008564,0.0,0.175115,0.099238,0.000000,0.000000,...,0.078448,0.055241,0.278876,0.032243,0.022218,0.121580,0.085519,0.058569,0.276222,0.078463
167779,0.0,0.014055,0.0,0.0,0.000000,0.0,0.150878,0.130387,0.000000,0.011059,...,0.074299,0.053778,0.168359,0.043058,0.024883,0.106284,0.094542,0.065982,0.259573,0.077460
167780,0.0,0.041095,0.0,0.0,0.003728,0.0,0.148428,0.106508,0.000000,0.000000,...,0.066978,0.053370,0.304215,0.012127,0.019711,0.104122,0.115786,0.049744,0.251808,0.074468

In [11]:
st_df

,ABCC11,ACTA2,ACTG2,ADAM9,ADGRE5,ADH1B,ADIPOQ,AGR3,AHSP,AIF1,...,TUBB2B,TYROBP,UCP1,USP53,VOPP1,VWF,WARS,ZEB1,ZEB2,ZNF562
1,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.0,0.000000,...,0.0,0.000000,0.0,0.000000,0.000000,0.0,1.935654,0.0,0.000000,0.000000
2,0.000000,0.000000,1.017387,0.0,0.0,0.000000,0.0,1.511145,0.0,0.000000,...,0.0,0.000000,0.0,1.840212,0.000000,0.0,0.000000,0.0,0.000000,0.000000
3,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.0,0.000000,...,0.0,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000
4,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.0,0.000000,...,0.0,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000
5,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.0,2.068970,...,0.0,1.494775,0.0,2.068970,0.000000,0.0,0.000000,0.0,1.494775,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
167776,0.895999,0.545164,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.0,0.895999,...,0.0,0.000000,0.0,0.000000,0.895999,0.0,0.000000,0.0,0.000000,0.545164
167777,0.000000,1.131810,1.131810,0.0,0.0,0.000000,0.0,0.000000,0.0,0.000000,...,0.0,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000
167778,0.983031,0.349343,1.128391,0.0,0.0,0.000000,0.0,0.349343,0.0,0.000000,...,0.0,0.000000,0.0,0.607737,0.607737,0.0,0.000000,0.0,0.000000,0.812887
167779,0.883273,0.000000,0.000000,0.0,0.0,0.883273,0.0,0.000000,0.0,0.000000,...,0.0,0.000000,0.0,0.883273,0.000000,0.0,0.000000,0.0,0.000000,0.000000
167780,1.014003,0.364055,0.840472,0.0,0.0,0.000000,0.0,0.364055,0.0,0.000000,...,0.0,0.000000,0.0,0.000000,0.840472,0.0,0.000000,0.0,0.000000,0.000000

In [12]:
# Create a new AnnData object with the imputed genes
import numpy as np

# First, check if there are any overlapping genes between the original data and imputed genes
overlapping_genes = np.intersect1d(st_df.columns, imputed_genes.columns)
if len(overlapping_genes) > 0:
    print(f"Warning: Found {len(overlapping_genes)} overlapping genes between original data and imputed genes.")
    print("These genes will be taken from the original data.")

# Create a combined dataframe with both original and imputed genes
# Use axis=1 to concatenate columns (genes) not rows
combined_df = pd.concat([st_df, imputed_genes.loc[st_df.index]], axis=1)

# If there are duplicated columns, keep the first occurrence (from original data)
if combined_df.columns.duplicated().any():
    combined_df = combined_df.loc[:, ~combined_df.columns.duplicated()]

print(f"Original data shape: {st_df.shape}")
print(f"Imputed genes shape: {imputed_genes.shape}")
print(f"Combined data shape: {combined_df.shape}")

# Verify that the row count matches the original data
assert combined_df.shape[0] == st_df.shape[0], "Row count mismatch after concatenation"
# Verify that the column count is the sum of unique genes
assert combined_df.shape[1] == len(set(st_df.columns) | set(imputed_genes.columns)), "Column count mismatch"

Original data shape: (167780, 313)
Imputed genes shape: (167780, 17772)
Combined data shape: (167780, 18085)

In [13]:
combined_df = combined_df.astype(np.float16)

In [14]:
# Check the data type of combined_df
print("Data type of combined_df:")
print(f"DataFrame dtype: {combined_df.dtypes.value_counts()}")
print(f"Memory usage: {combined_df.memory_usage().sum() / 1e6:.2f} MB")

Data type of combined_df:
DataFrame dtype: float16    18085
Name: count, dtype: int64

Memory usage: 6074.17 MB

In [15]:
st_data_path = '../dataset/Xenium_breast_cancer_sample1_replicate1.h5ad'
original_st_data = sc.read_h5ad(st_data_path)
imputed_st_data = sc.AnnData(X=combined_df, 
                             obs=original_st_data.obs,
                             uns=original_st_data.uns
                             )
imputed_st_data.uns['COVET_genes'] = imputed_genes.columns.tolist()
imputed_st_data.write_h5ad('../dataset/SpaGE_imputed_Xenium_breast_cancer_sample1_replicate1.h5ad')

In [16]:
imputed_st_data.X.sum(axis=1)

array([ 952.5,  978.5,  746. , ..., 1003. ,  963. , 1026. ], dtype=float16)